--Joshua Farr

--1
ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDERS_USER
FOREIGN KEY (USERID) REFERENCES USERBASE(USERID);

ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDERS_PRODUCT
FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCTLIST(PRODUCTCODE);

ALTER TABLE REVIEWS
ADD CONSTRAINT FK_REVIEWS_USER
FOREIGN KEY (USERID) REFERENCES USERBASE(USERID);

ALTER TABLE REVIEWS
ADD CONSTRAINT FK_REVIEWS_PRODUCT
FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCTLIST(PRODUCTCODE);

ALTER TABLE USERLIBRARY
ADD CONSTRAINT FK_USERLIBRARY_USER
FOREIGN KEY (USERID) REFERENCES USERBASE(USERID);

ALTER TABLE USERLIBRARY
ADD CONSTRAINT FK_USERLIBRARY_PRODUCT
FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCTLIST(PRODUCTCODE);

--2
SELECT FIRSTNAME || ' ' || LASTNAME AS FULLNAME, USERNAME
FROM USERBASE
WHERE MONTHS_BETWEEN(SYSDATE, BIRTHDAY)/12 >= 18;

--3
SELECT MAX(LENGTH(USERNAME)) AS MAX_USERNAME_LENGTH,
       AVG(LENGTH(USERNAME)) AS AVG_USERNAME_LENGTH
FROM USERBASE;

--4 
SELECT QUESTION
FROM SECURITYQUESTION
WHERE QUESTION LIKE 'What is%' OR QUESTION LIKE 'What was%';

--5
SELECT PRODUCTCODE,
       MIN(RATING) AS LOWEST_RATING,
       COUNT(*) AS REVIEW_COUNT
FROM REVIEWS
GROUP BY PRODUCTCODE
ORDER BY REVIEW_COUNT DESC;

--6
SELECT PRODUCTCODE,
       COUNT(*) AS NUMBER_OF_USERS
FROM WISHLIST
WHERE POSITION = 1
GROUP BY PRODUCTCODE;

--7
SELECT USERID,
       SUM(PRICE) AS TOTAL_SPENT
FROM ORDERS
GROUP BY USERID;

--8
SELECT PURCHASEDATE,
       SUM(PRICE) AS GROSS_PROFIT
FROM ORDERS
GROUP BY PURCHASEDATE
ORDER BY GROSS_PROFIT DESC;

--9
SELECT PRODUCTCODE,
       SUM(HOURSPLAYED) AS TOTAL_HOURS_PLAYED
FROM USERLIBRARY
GROUP BY PRODUCTCODE
ORDER BY TOTAL_HOURS_PLAYED DESC
FETCH FIRST 5 ROWS ONLY;

--10
CREATE OR REPLACE VIEW UserInfractionCount AS
SELECT USERID,
       COUNT(*) AS INFRACTION_COUNT
FROM INFRACTIONS
GROUP BY USERID
ORDER BY INFRACTION_COUNT DESC;

--11
CREATE OR REPLACE VIEW UserRuleBreakCount AS
SELECT USERID,
       RULENUM,
       COUNT(*) AS TIMES_BROKEN
FROM INFRACTIONS
GROUP BY USERID, RULENUM
ORDER BY USERID;

--12
SELECT RULENUM,
       PENALTY,
       COUNT(*) AS TIMES_ASSIGNED
FROM INFRACTIONS
GROUP BY RULENUM, PENALTY;

--13
SELECT AVG(DATEUPDATED - DATESUBMITTED) AS AVG_TURNAROUND_DAYS,
       MAX(DATEUPDATED - DATESUBMITTED) AS MAX_TURNAROUND_DAYS,
       MIN(DATEUPDATED - DATESUBMITTED) AS MIN_TURNAROUND_DAYS
FROM USERSUPPORT
WHERE STATUS = 'CLOSED';

--14
SELECT EMAIL,
       ISSUE,
       COUNT(*) AS ISSUE_COUNT
FROM USERSUPPORT
WHERE STATUS = 'NEW'
GROUP BY DATESUBMITTED, EMAIL, ISSUE
ORDER BY ISSUE_COUNT DESC;

--15
SELECT USERID, FIRSTNAME, LASTNAME
FROM USERBASE
WHERE PASSWORD LIKE '%' || FIRSTNAME || '%'
   OR PASSWORD LIKE '%' || LASTNAME || '%';

--16
SELECT PUBLISHER,
       AVG(PRICE) AS AVG_PRICE
FROM PRODUCTLIST
GROUP BY PUBLISHER
ORDER BY PUBLISHER ASC;

--17
CREATE OR REPLACE VIEW DiscountedOldProducts AS
SELECT PRODUCTNAME,
       PRICE * 0.75 AS DISCOUNTED_PRICE
FROM PRODUCTLIST
WHERE RELEASEDATE <= ADD_MONTHS(SYSDATE, -60);

--18
SELECT GENRE,
       MAX(PRICE) AS MAX_PRICE,
       MIN(PRICE) AS MIN_PRICE
FROM PRODUCTLIST
GROUP BY GENRE;

--19
CREATE OR REPLACE VIEW RecentChatLog AS
SELECT *
FROM CHATLOG
WHERE DATESENT BETWEEN SYSDATE - 7 AND SYSDATE;

--20
CREATE OR REPLACE VIEW RecentPenalties AS
SELECT USERID,
       DATEASSIGNED,
       PENALTY
FROM INFRACTIONS
WHERE PENALTY IS NOT NULL
  AND DATEASSIGNED >= ADD_MONTHS(SYSDATE, -1);